{"uuid": "de85427f-e373-473a-8d87-d9d4df22fad0", "children": ["01bdc17e-89ac-4e01-a64b-bc4dc8809741"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 90\nCurrent browser version is 92.0.4515.107 with binary path C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe\n\n", "trace": "  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\_pytest\\fixtures.py\", line 918, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\_pytest\\fixtures.py\", line 774, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\Владимир\\PycharmProjects\\autotest_staging\\CS\\conftest.py\", line 27, in browser\n    browser = webdriver.Chrome(options=options)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 75, in __init__\n    desired_capabilities=desired_capabilities)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 156, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 251, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 320, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Владимир\\environments\\selenium_env\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1627560029807, "stop": 1627560033157}], "start": 1627560029807, "stop": 1627560033219}